import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <head>
        <link rel="stylesheet" href="/font-awesome-4.7.0/css/font-awesome.min.css"></link>
      </head>
      <body>{children}</body>
    </html>
  );
}
