import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import localFont from "neext/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazirFont = localFont({
  src: [
    {
      path: "./font/webfronts/._Vazirmatn-Regular.woff2",
      weight: "400",
      style : "normal"
    },
  ],
  variable :"--font-vazirFont",
});

export default function RootLayout({ children }) {
  return (
    <html lang="fa" className={vazirFont.variable}>
      <head>
        <link
          rel="stylesheet"
          href="/font-awesome-4.7.0/css/font-awesome.min.css"
        ></link>
      </head>
      <body>{children}</body>
    </html>
  );
}
