import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import MainHeader from "./components/ui/home/MainHeader";
// import localFont from "next/font/local";

export const metadata = {
  title: "دیوار",
  description: "Generated by create next app",
};

// const vazirFont = localFont({
//   src: [
//     {
//       path: "./fonts/fonts/webfronts/Vazirmatn-Regular.woff2",
//       weight: "400",
//       style : "normal"
//     },
//   ],
//   variable :"--font-vazirFont",
// });

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <head>
        <link
          rel="stylesheet"
          href="/font-awesome-4.7.0/css/font-awesome.min.css"
        ></link>
      </head>
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
